In [3]:
import pandas as pd
import os

In [4]:
# Training data
train_s1 = pd.read_csv("../dataset/train/train_source1.tsv", sep="\t")
train_s2 = pd.read_csv("../dataset/train/train_source2.tsv", sep="\t")
train_s3 = pd.read_csv("../dataset/train/train_source3.tsv", sep="\t")
ground_truth = pd.read_csv("../dataset/train/train_ground_truth.tsv", sep="\t")

# Test data
test_s1 = pd.read_csv("../dataset/test/test_source1.tsv", sep="\t")
test_s2 = pd.read_csv("../dataset/test/test_source2.tsv", sep="\t")
test_s3 = pd.read_csv("../dataset/test/test_source3.tsv", sep="\t")

In [5]:
datasets = {
    "train_source1": train_s1,
    "train_source2": train_s2,
    "train_source3": train_s3,
    "ground_truth": ground_truth,
    "test_source1": test_s1,
    "test_source2": test_s2,
    "test_source3": test_s3
}

for name, df in datasets.items():
    print(f"\n{name}")
    print("Shape:", df.shape)
    print("Columns:", list(df.columns))

train_source1
Shape: (2206821, 4)
Columns: ['entity_id', 'business_name', 'business_address', 'country']

train_source2
Shape: (5034616, 4)
Columns: ['entity_id', 'business_name', 'business_address', 'country']

train_source3
Shape: (5285603, 4)
Columns: ['entity_id', 'business_name', 'business_address', 'country']

ground_truth
Shape: (2206821, 2)
Columns: ['source1_entity_id', 'matched_entity_ids']

test_source1
Shape: (1732544, 4)
Columns: ['entity_id', 'business_name', 'business_address', 'country']

test_source2
Shape: (4887273, 4)
Columns: ['entity_id', 'business_name', 'business_address', 'country']

test_source3
Shape: (5082316, 4)
Columns: ['entity_id', 'business_name', 'business_address', 'country']

In [6]:
for name, df in datasets.items():
    print(f"\n===== {name} =====")
    print(df.isnull().sum())

===== train_source1 =====
entity_id           0
business_name       0
business_address    0
country             0
dtype: int64

===== train_source2 =====
entity_id                0
business_name            2
business_address    168967
country                  0
dtype: int64

===== train_source3 =====
entity_id                0
business_name           13
business_address    175916
country                  0
dtype: int64

===== ground_truth =====
source1_entity_id          0
matched_entity_ids    123247
dtype: int64

===== test_source1 =====
entity_id           0
business_name       0
business_address    0
country             0
dtype: int64

===== test_source2 =====
entity_id                0
business_name           46
business_address    129408
country                  0
dtype: int64

===== test_source3 =====
entity_id                0
business_name           59
business_address    136098
country                  0
dtype: int64

In [7]:
for name, df in datasets.items():
    print(f"{name}: {df.duplicated().sum()} duplicate rows")

train_source1: 0 duplicate rows
train_source2: 0 duplicate rows
train_source3: 0 duplicate rows
ground_truth: 0 duplicate rows
test_source1: 0 duplicate rows
test_source2: 0 duplicate rows
test_source3: 0 duplicate rows

In [8]:
for name, df in datasets.items():
    if "entity_id" in df.columns:
        print(f"{name}: {df['entity_id'].duplicated().sum()} duplicate entity IDs")

train_source1: 0 duplicate entity IDs
train_source2: 0 duplicate entity IDs
train_source3: 0 duplicate entity IDs
test_source1: 0 duplicate entity IDs
test_source2: 0 duplicate entity IDs
test_source3: 0 duplicate entity IDs

In [9]:
for name in ["train_source1", "train_source2", "train_source3",
             "test_source1", "test_source2", "test_source3"]:
    print(f"\n===== {name} =====")
    print(datasets[name]["country"].value_counts(dropna=False))

===== train_source1 =====
country
US       1323633
India     883188
Name: count, dtype: int64

===== train_source2 =====
country
US       3016817
India    2017799
Name: count, dtype: int64

===== train_source3 =====
country
US       3170056
India    2115547
Name: count, dtype: int64

===== test_source1 =====
country
India     809986
US        663106
France    259452
Name: count, dtype: int64

===== test_source2 =====
country
India     2312565
US        1871330
France     703378
Name: count, dtype: int64

===== test_source3 =====
country
India     2405000
US        1945701
France     731615
Name: count, dtype: int64

In [10]:
from sys import path
path.append("../src")

from preprocessing import normalize_text, normalize_name, normalize_address

print(normalize_name("McDonald's, Hyderabad!"))
print(normalize_address("12, M.G. Road, Hyderabad"))

mcdonald s hyderabad
12 m g road hyderabad

In [11]:
print("===== SAMPLE BUSINESS NAMES =====")
display(train_s1[["business_name", "business_address", "country"]].head(10))

print("\n===== MISSING ADDRESS EXAMPLES =====")
display(train_s2[train_s2["business_address"].isna()][
    ["business_name", "business_address", "country"]
].head(10))

===== SAMPLE BUSINESS NAMES =====

,business_name,business_address,country
0,Orelee's Barbershop,"1795 Westchester Drive, High Point, NC",US
1,Prime Money,"17560 Ellis Road, Tahlequah, OK",US
2,B+ Retail Inc,"1712 Montebello Avenue, Phoenix, AZ",US
3,Christ Chapel,"2100 Cameron Drive, Unit APARTMENT G, Dundalk, MD",US
4,Prabhav Business Center,"797, Lake Town Block A, Kolkata, Howrah, West ...",India
5,Custom Wealth Services LLC,"OH, Columbus, 5559 Orville Avenue",US
6,Consulting Nyasa Nursing Private Limited,"2505, Tower 1, Oakwood, Runwal Greens, Mulund ...",India
7,Nexus Anchor Rain,"1111 Church Street, Unit 2007, Nashville, TN",US
8,Moore Bitwise Inc,"337 Oakland Avenue, Michigan City, IN",US
9,Dermatology Green Medicine,"294 Meadowcreek Drive, Unit Unit 2, Village Of...",US

===== MISSING ADDRESS EXAMPLES =====

                           business_name business_address country
53         Guerra And Krueger Table, LLC              NaN      US
69                   L E Pierce Cal [PC]              NaN      US
93             Preferred Bay Montage Inc              NaN      US
195              DELONG STRATEGIC  READY              NaN      US
236      Desert Vanguard ([Maintenance])              NaN      US
346                     Wildlife Sóciety              NaN      US
352                  Orellana Kensington              NaN      US
376                       rathi holdings              NaN   India
390                           Berry Saul              NaN      US
424  Thrasher, Wanner 5tenson LLC Center              NaN      US